### ISSUE TITLE
Client-side Error occurred 🚀 

### ISSUE THREAD

**Issue by bbonkr** [bbonkr/resume#276]
### Description

```
s of null (reading 'content')
    at r (main-4dcb7f9b52833aba.js:1:6170)
    at main-4dcb7f9b52833aba.js:1:5156
    at Array.forEach (<anonymous>)
    at Object.updateHead (main-4dcb7f9b52833aba.js:1:5144)
    at Object.l [as _pendingUpdate] (main-4dcb7f9b52833aba.js:1:80215)
    at main-4dcb7f9b52833aba.js:1:80560
    at uI (framework-cda2f1305c3d9424.js:9:84128)
    at oU (framework-cda2f1305c3d9424.js:9:113199)
    at o (framework-cda2f1305c3d9424.js:9:107746)
    at x (framework-cda2f1305c3d9424.js:33:1373)
K @ main-4dcb7f9b52833aba.js:1
```

**Comment by bbonkr** [comment]
- https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary
- https://nextjs.org/docs/advanced-features/custom-error-page#more-advanced-error-page-customizing
- https://nextjs.org/docs/advanced-features/error-handling#handling-client-errors

**Comment by bbonkr** [comment]
- https://www.netlify.com/blog/nextjs-advanced-middleware-better-runtime-that-extends-nextjs/
